Excavator:
  - id: excavator1
    type: excavator
    offset: 
      x: 0.75
      y: 1
      z: 0.75
    rotation: 
      x: 0
      y: 0
      z: 0
    sensors:
      - id: Chasis_IMU
        type: IMU
        topic: /imu_chasis
        # unit: radians
        location: CHASIS
        noise:
          mean: 0.1
          std_dev: 0.01
        offset: 
          x: 0.3436
          y: 0.15
          z: -0.2921
        rotation: 
          x: 0
          y: -90
          z: 90
  
  - id: excavator2
    type: excavator
    offset: 
      x: 5
      y: 1
      z: 0
    rotation: 
      x: 0
      y: 0
      z: 0
    sensors:
      - id: Chasis_IMU
        type: IMU
        topic: /imu_chasis
        # unit: radians
        location: CHASIS
        noise:
          mean: 0.1
          std_dev: 0.01
        offset: 
          x: 0.3436
          y: 0.15
          z: -0.2921
        rotation: 
          x: 0
          y: -90
          z: 90

  # - id: excavator3
  #   type: excavator
  #   offset: 
  #     x: -5
  #     y: 2
  #     z: -5
  #   rotation: 
  #     x: 0
  #     y: 0
  #     z: 0
  
  # - id: excavator4
  #   type: excavator
  #   offset: 
  #     x: 5
  #     y: 2
  #     z: -5
  #   rotation: 
  #     x: 0
  #     y: 0
  #     z: 0

  # - id: excavator5
  #   type: excavator
  #   offset: 
  #     x: -5
  #     y: 2
  #     z: 5
  #   rotation: 
  #     x: 0
  #     y: 0
  #     z: 0

  # - id: excavator6
  #   type: excavator
  #   offset: 
  #     x: 5
  #     y: 2
  #     z: 0.75
  #   rotation: 
  #     x: 0
  #     y: 0
  #     z: 0
  
  # - id: excavator7
  #   type: excavator
  #   offset: 
  #     x: -5
  #     y: 2
  #     z: 0.75
  #   rotation: 
  #     x: 0
  #     y: 0
  #     z: 0

  # - id: excavator8
  #   type: excavator
  #   offset: 
  #     x: 0.75
  #     y: 2
  #     z: 5
  #   rotation: 
  #     x: 0
  #     y: 0
  #     z: 0
  
  # - id: excavator9
  #   type: excavator
  #   offset: 
  #     x: 0.75
  #     y: 2
  #     z: -5
  #   rotation: 
  #     x: 0
  #     y: 0
  #     z: 0

  # - id: excavator10
  #   type: excavator
  #   offset: 
  #     x: 1
  #     y: 2
  #     z: -10
  #   rotation: 
  #     x: 0
  #     y: 0
  #     z: 0