Excavator:
  - id: excavator1
    type: excavator
    offset: 
      x: 0.75
      y: 1
      z: 0.75
    rotation: 
      x: 0
      y: 0
      z: 0
  
  - id: excavator2
    type: excavator
    offset: 
      x: 5
      y: 1
      z: 5
    rotation: 
      x: 0
      y: 0
      z: 0

  - id: excavator3
    type: excavator
    offset: 
      x: -5
      y: 1
      z: -5
    rotation: 
      x: 0
      y: 0
      z: 0
  
  # - id: excavator4
  #   type: excavator
  #   offset: 
  #     x: 5
  #     y: 1
  #     z: -5
  #   rotation: 
  #     x: 0
  #     y: 0
  #     z: 0

  # - id: excavator5
  #   type: excavator
  #   offset: 
  #     x: -5
  #     y: 1
  #     z: 5
  #   rotation: 
  #     x: 0
  #     y: 0
  #     z: 0

  # - id: excavator6
  #   type: excavator
  #   offset: 
  #     x: 5
  #     y: 1
  #     z: 0.75
  #   rotation: 
  #     x: 0
  #     y: 0
  #     z: 0
  
  # - id: excavator7
  #   type: excavator
  #   offset: 
  #     x: -5
  #     y: 1
  #     z: 0.75
  #   rotation: 
  #     x: 0
  #     y: 0
  #     z: 0

  # - id: excavator8
  #   type: excavator
  #   offset: 
  #     x: 0.75
  #     y: 1
  #     z: 5
  #   rotation: 
  #     x: 0
  #     y: 0
  #     z: 0
  
  # - id: excavator9
  #   type: excavator
  #   offset: 
  #     x: 0.75
  #     y: 1
  #     z: -5
  #   rotation: 
  #     x: 0
  #     y: 0
  #     z: 0

  # - id: excavator10
  #   type: excavator
  #   offset: 
  #     x: 1
  #     y: 1
  #     z: -10
  #   rotation: 
  #     x: 0
  #     y: 0
  #     z: 0