//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Deltacan
{
    [Serializable]
    public class DeltaCanMsg : Message
    {
        public const string k_RosMessageName = "deltacan/DeltaCan";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public float mslewcmd;
        public float mboomcmd;
        public float mbucketcmd;
        public float marmcmd;
        public float mlefttravelcmd;
        public float mrighttravelcmd;
        public float mbladecmd_a;
        public float mswingcmd_a;
        public float mthumbcmd_a;
        public float mbladecmd_b;
        public float mswingcmd_b;
        public float mthumbcmd_b;
        public float mhydraulic;
        public float mhorn;
        public float menableautonav;

        public DeltaCanMsg()
        {
            this.header = new Std.HeaderMsg();
            this.mslewcmd = 0.0f;
            this.mboomcmd = 0.0f;
            this.mbucketcmd = 0.0f;
            this.marmcmd = 0.0f;
            this.mlefttravelcmd = 0.0f;
            this.mrighttravelcmd = 0.0f;
            this.mbladecmd_a = 0.0f;
            this.mswingcmd_a = 0.0f;
            this.mthumbcmd_a = 0.0f;
            this.mbladecmd_b = 0.0f;
            this.mswingcmd_b = 0.0f;
            this.mthumbcmd_b = 0.0f;
            this.mhydraulic = 0.0f;
            this.mhorn = 0.0f;
            this.menableautonav = 0.0f;
        }

        public DeltaCanMsg(Std.HeaderMsg header, float mslewcmd, float mboomcmd, float mbucketcmd, float marmcmd, float mlefttravelcmd, float mrighttravelcmd, float mbladecmd_a, float mswingcmd_a, float mthumbcmd_a, float mbladecmd_b, float mswingcmd_b, float mthumbcmd_b, float mhydraulic, float mhorn, float menableautonav)
        {
            this.header = header;
            this.mslewcmd = mslewcmd;
            this.mboomcmd = mboomcmd;
            this.mbucketcmd = mbucketcmd;
            this.marmcmd = marmcmd;
            this.mlefttravelcmd = mlefttravelcmd;
            this.mrighttravelcmd = mrighttravelcmd;
            this.mbladecmd_a = mbladecmd_a;
            this.mswingcmd_a = mswingcmd_a;
            this.mthumbcmd_a = mthumbcmd_a;
            this.mbladecmd_b = mbladecmd_b;
            this.mswingcmd_b = mswingcmd_b;
            this.mthumbcmd_b = mthumbcmd_b;
            this.mhydraulic = mhydraulic;
            this.mhorn = mhorn;
            this.menableautonav = menableautonav;
        }

        public static DeltaCanMsg Deserialize(MessageDeserializer deserializer) => new DeltaCanMsg(deserializer);

        private DeltaCanMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.mslewcmd);
            deserializer.Read(out this.mboomcmd);
            deserializer.Read(out this.mbucketcmd);
            deserializer.Read(out this.marmcmd);
            deserializer.Read(out this.mlefttravelcmd);
            deserializer.Read(out this.mrighttravelcmd);
            deserializer.Read(out this.mbladecmd_a);
            deserializer.Read(out this.mswingcmd_a);
            deserializer.Read(out this.mthumbcmd_a);
            deserializer.Read(out this.mbladecmd_b);
            deserializer.Read(out this.mswingcmd_b);
            deserializer.Read(out this.mthumbcmd_b);
            deserializer.Read(out this.mhydraulic);
            deserializer.Read(out this.mhorn);
            deserializer.Read(out this.menableautonav);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.mslewcmd);
            serializer.Write(this.mboomcmd);
            serializer.Write(this.mbucketcmd);
            serializer.Write(this.marmcmd);
            serializer.Write(this.mlefttravelcmd);
            serializer.Write(this.mrighttravelcmd);
            serializer.Write(this.mbladecmd_a);
            serializer.Write(this.mswingcmd_a);
            serializer.Write(this.mthumbcmd_a);
            serializer.Write(this.mbladecmd_b);
            serializer.Write(this.mswingcmd_b);
            serializer.Write(this.mthumbcmd_b);
            serializer.Write(this.mhydraulic);
            serializer.Write(this.mhorn);
            serializer.Write(this.menableautonav);
        }

        public override string ToString()
        {
            return "DeltaCanMsg: " +
            "\nheader: " + header.ToString() +
            "\nmslewcmd: " + mslewcmd.ToString() +
            "\nmboomcmd: " + mboomcmd.ToString() +
            "\nmbucketcmd: " + mbucketcmd.ToString() +
            "\nmarmcmd: " + marmcmd.ToString() +
            "\nmlefttravelcmd: " + mlefttravelcmd.ToString() +
            "\nmrighttravelcmd: " + mrighttravelcmd.ToString() +
            "\nmbladecmd_a: " + mbladecmd_a.ToString() +
            "\nmswingcmd_a: " + mswingcmd_a.ToString() +
            "\nmthumbcmd_a: " + mthumbcmd_a.ToString() +
            "\nmbladecmd_b: " + mbladecmd_b.ToString() +
            "\nmswingcmd_b: " + mswingcmd_b.ToString() +
            "\nmthumbcmd_b: " + mthumbcmd_b.ToString() +
            "\nmhydraulic: " + mhydraulic.ToString() +
            "\nmhorn: " + mhorn.ToString() +
            "\nmenableautonav: " + menableautonav.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
